### PR TITLE
Fallback implementations of sigaddset & sigemptyset

### PR DESCRIPTION
**Pull request by vorner**
For certain android systems that are missing them.

### CODE REVIEW

**Comment by Hocuri** [comment]
Unfortunately, this PR does not help. I get the same linking error as in #118 (I double-checked that if I switch to my `Hocuri:patch-1` branch from #121 instead of `android-hack`, it links fine again)

**Comment by vorner** [comment]
@Hocuri Can you check this new version? It doesn't use the linker dark magic like the previous one, but at least tries to do the same thing as the missing functions.

**Comment by Hocuri** [comment]
Yes, it works now, thanks a lot :tada::heart::heart::heart:!

**Comment by vorner** [comment]
> Note though that I can't actually test anything, just see that it compiles and links fine.

That's better than me… so, let's hope this is working. If not, I guess there'll be another bug report soon :shrug:

**Pull request merged**
