### PR TITLE
update to rust 2018

### PR DESCRIPTION
**Pull request by jjakobh**

### CODE REVIEW

**Comment by vorner** [comment]
Hello

Can I ask for the motivation behind this?

The crate currently tries to support Rust 1.26 (which is the one in Debian). I know that one is old, but it doesn't really *need* any of the newer features. So if updating to Rust 2018 is just because of aesthetics, I don't think dropping the old support is worth it.

**Comment by jjakobh** [comment]
I wanted to give updating `signal-hook` to Tokio 0.2 a try and do this before because I assumed Tokios MSRV would be higher, but now I cant find tokios policy on rust versions so I'm not sure where I got that idea from.

**Comment by vorner** [comment]
That makes some sense. Though, I'd like to point out that tokio is only optional dependency. So even if support for tokio 0.2 is added, it is possible to support 1.26 without it enabled.

But I'm probably willing to talk about bumping the minimal version for signal-hook itself, especially if updating to tokio 0.2 requires a major version bump/API breackage. On the other hand, I'd still like to keep the signal-hook-registry compatible.

**Comment by jjakobh** [comment]
sure, makes sense

**Comment by vorner** [comment]
Oh, by the way, if you want to work on the tokio 0.2 support, I'd suggest you write a comment to #24 and claim it (or, I can just assign you there). Just to prevent duplicate effort. And any such effort in that direction will be appreciated :-).

**Pull request closed without merging**
